### ISSUE TITLE
[Feature Request] Manage product backlog items

### ISSUE THREAD

**Issue by gomaltao** [Microsoft/azure-devops-cli-extension#470] opened 2019-03-01 13:14 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I cannot create a project..

**Describe the solution you'd like**
e.g. If you want a new command to be added, what would it do?

**Additional context**
some aAPI to manage pbi:s

**Comment by atbagga** [comment] 2019-03-04 05:11
@gomaltao Can you share some more details on what commands you are looking for and what scenario you are trying to target? 

Filling in the template will help.

**Comment by gomaltao** [comment] 2019-03-04 14:11
Maybe I am a new user of devops but as I understand it it should be possible to link pbi:s to work-items and tasks. Is this possible to do in azure decli devops extension?

**Comment by atbagga** [comment] 2019-03-07 09:21
@gomaltao Product Backlog Item is just a type of workitem in azure boards. 
You can manage PBI:s using regular az boards commands in azure-devops-cli-extension.

e.g. This command will create a PBI for you -
`az boards work-item create --title 'title for the item' --type 'product backlog item'`
Similarly you can use show, update and delete commands as well to manage PBIs.

For linking the PBIs to tasks yas that is possible in azure devops(boards) but that is not supported in the CLI yet. 
If that is the requirement you want to post please edit the title/description or let me know and I will change the Feature request appropriately.

**Comment by gomaltao** [comment] 2019-03-07 10:44
atbagga, that is exactly what I wish for. Here at work we create a lot of product backlog items and then we create related tasks that we need to link to pbis:.

**Comment by gomaltao** [comment] 2019-03-07 10:46
I closed this issue by mistake.

**Comment by atbagga** [comment] 2019-03-07 11:33
@gomaltao  In that case this is a duplicate of issue #93 
This is being worked upon already in pull request #125 

Closing the issue. Follow issue #93 for updates. Hopefully this should land soon.

**Closed by atbagga** 2019-03-07 11:33 UTC
Labels: Feature
